##Pandas : It is a fast,powerful,flexible and easy to use open source data analysis and manipulation tool,built on top ofthe Python

##Pandas series: It is like a column in table .It is a 1D array holding data of any type

In [1]:
# importing pandas
import pandas as pd
import numpy as np

##Series from lists

In [2]:
#String
country=["India","Pakistan","USA","Nepal","Srilanka"]
pd.Series(country)

0       India
1    Pakistan
2         USA
3       Nepal
4    Srilanka
dtype: str

In [3]:
#Integer
runs=[12,13,15,17,18,19,19]
pd.Series(runs)

0    12
1    13
2    15
3    17
4    18
5    19
6    19
dtype: int64

In [4]:
#Custom index
marks=[65,78,29,98]
subjects=["Maths","English","Science","Hindi"]
pd.Series(marks,index=subjects)

Maths      65
English    78
Science    29
Hindi      98
dtype: int64

In [5]:
#Setting a name
pd.Series(marks,index=subjects,name="simran ke marks")

Maths      65
English    78
Science    29
Hindi      98
Name: simran ke marks, dtype: int64

##Series from dict

In [16]:
marks={"Maths":67,"English":78,"Hindi":90,"Science":89}
marks_series=pd.Series(marks,name="simran ke marks")
marks_series

Maths      67
English    78
Hindi      90
Science    89
Name: simran ke marks, dtype: int64

##Series Attributes

In [22]:
#size=Number of items in series
marks_series.size

4

In [23]:
#dtype=type of the elemnets in series
marks_series.dtype

dtype('int64')

In [24]:
#name=The we added in the name section of the code
marks_series.name

'simran ke marks'

In [28]:
#is_unique=It will gives true value for unique numbers in series but if it sees the repeated number than gives false
marks_series.is_unique

True

In [29]:
#index=Gives the index values
marks_series.index

Index(['Maths', 'English', 'Hindi', 'Science'], dtype='str')

In [31]:
#value=Gives numpy array
marks_series.values

array([67, 78, 90, 89])

##Series using read_csv

In [7]:
#with one col
subs=pd.read_csv('subs.csv')
subs

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [8]:
#with two cols
vk=pd.read_csv('kohli_ipl.csv')
vk

     match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

In [9]:
#importing movie data
#reading the file
bollywood=pd.read_csv('bollywood.csv')
bollywood

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]

In [39]:
#making series of movie column
bollywood=bollywood['movie']
bollywood

0                   Uri: The Surgical Strike
1                              Battalion 609
2       The Accidental Prime Minister (film)
3                            Why Cheat India
4                            Evening Shadows
                        ...
1495                  Hum Tumhare Hain Sanam
1496                     Aankhen (2002 film)
1497                         Saathiya (film)
1498                          Company (film)
1499                    Awara Paagal Deewana
Name: movie, Length: 1500, dtype: str

In [24]:
#making the lead column
bollywood=bollywood['lead']
bollywood

0          Vicky Kaushal
1            Vicky Ahuja
2            Anupam Kher
3          Emraan Hashmi
4       Mona Ambegaonkar
              ...
1495      Shah Rukh Khan
1496    Amitabh Bachchan
1497        Vivek Oberoi
1498          Ajay Devgn
1499        Akshay Kumar
Name: lead, Length: 1500, dtype: str

In [25]:
#making lead column->index
bollywood=pd.read_csv('bollywood.csv',index_col='lead')
bollywood

                                                 movie
lead
Vicky Kaushal                 Uri: The Surgical Strike
Vicky Ahuja                              Battalion 609
Anupam Kher       The Accidental Prime Minister (film)
Emraan Hashmi                          Why Cheat India
Mona Ambegaonkar                       Evening Shadows
...                                                ...
Shah Rukh Khan                  Hum Tumhare Hain Sanam
Amitabh Bachchan                   Aankhen (2002 film)
Vivek Oberoi                           Saathiya (film)
Ajay Devgn                              Company (film)
Akshay Kumar                      Awara Paagal Deewana

[1500 rows x 1 columns]

In [26]:
#making lead column->index
bollywood=pd.read_csv('bollywood.csv',index_col='movie')
bollywood

                                                  lead
movie
Uri: The Surgical Strike                 Vicky Kaushal
Battalion 609                              Vicky Ahuja
The Accidental Prime Minister (film)       Anupam Kher
Why Cheat India                          Emraan Hashmi
Evening Shadows                       Mona Ambegaonkar
...                                                ...
Hum Tumhare Hain Sanam                  Shah Rukh Khan
Aankhen (2002 film)                   Amitabh Bachchan
Saathiya (film)                           Vivek Oberoi
Company (film)                              Ajay Devgn
Awara Paagal Deewana                      Akshay Kumar

[1500 rows x 1 columns]

##Series Methods

In [13]:
#head=gives the top five rows
subs.head()
vk.head(3) #this gives the first 3 rows

   match_no  runs
0         1     1
1         2    23
2         3    13

In [14]:
#tail = This gives last five matches
vk.tail(5)

     match_no  runs
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

In [27]:
#sample=Randomally gives 1 row 
bollywood.sample()

                        lead
movie
Action Replayy  Akshay Kumar

In [28]:
#value_counts=Give number of time the elements has repeat 
bollywood.value_counts()

lead
Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
                    ..
Tanishaa Mukerji     1
Tanuja               1
Ankit                1
Rakhee Gulzar        1
Edwin Fernandes      1
Name: count, Length: 566, dtype: int64

In [36]:
#sort_index=means it sort in ascending order
vk.sort_index(ascending=True)

     match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

In [39]:
#permanently sorting the index of movies
bollywood.sort_index(inplace=True)
bollywood

                                        lead
movie
1920 (film)                 Rajniesh Duggall
1920: London                   Sharman Joshi
1920: The Evil Returns           Vicky Ahuja
1971 (2007 film)              Manoj Bajpayee
2 States (2014 film)            Arjun Kapoor
...                                      ...
Zindagi 50-50                    Veena Malik
Zindagi Na Milegi Dobara      Hrithik Roshan
Zindagi Tere Naam         Mithun Chakraborty
Zokkomon                     Darsheel Safary
Zor Lagaa Ke...Haiya!          Meghan Jadhav

[1500 rows x 1 columns]

##Series Maths Method

In [3]:
#count=Total number of item present in series
vk.count()

match_no    215
runs        215
dtype: int64

In [ ]:
#sum 
subs.sum()

Subscribers gained    49510
dtype: int64

In [6]:
#product
subs.product()

Subscribers gained    0
dtype: int64

##Statistical Method

In [ ]:
#mean=average of the data
subs.mean()

Subscribers gained    135.643836
dtype: float64

In [11]:
#median=middle values
subs.median()

Subscribers gained    123.0
dtype: float64

In [ ]:
#mode=values repeated the most
subs.mode()

   Subscribers gained
0                 105

In [ ]:
#std=standard deviation
vk.std()

match_no    62.209324
runs        26.229801
dtype: float64

In [12]:
#var=variance of the value
vk.var()

match_no    3870.000000
runs         688.002478
dtype: float64

In [ ]:
#min=value which is minimum in dataset
subs.min()

Subscribers gained    33
dtype: int64

In [14]:
#max=value which is maximum in dataset
subs.max()

Subscribers gained    396
dtype: int64

In [15]:
#describe=describe the value
vk.describe()

         match_no        runs
count  215.000000  215.000000
mean   108.000000   30.855814
std     62.209324   26.229801
min      1.000000    0.000000
25%     54.500000    9.000000
50%    108.000000   24.000000
75%    161.500000   48.000000
max    215.000000  113.000000

##Series indexing

In [16]:
#integer imdexing
X=pd.Series([12,13,15,18,39,46])
X[1]

np.int64(13)

In [17]:
#slicing
vk[5:16]

    match_no  runs
5          6     9
6          7    34
7          8     0
8          9    21
9         10     3
10        11    10
11        12    38
12        13     3
13        14    11
14        15    50
15        16     2

In [18]:
#Negative slicing
vk[-5:]

     match_no  runs
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

In [24]:
#slicing 
#print the alternate match runs
vk[::2]

     match_no  runs
0           1     1
2           3    13
4           5     1
6           7    34
8           9    21
..        ...   ...
206       207     0
208       209    58
210       211     0
212       213    73
214       215     7

[108 rows x 2 columns]

In [35]:
#This is a data frame we need to convert it into series 
type(vk)

pandas.DataFrame

In [25]:

#converting vk into vk_series(we did this because fancy indexing was not working and we need to show that this is 1d data mens series data)
vk_series=vk['runs']
vk_series
type(vk_series)
vk_series

0       1
1      23
2      13
3      12
4       1
       ..
210     0
211    20
212    73
213    25
214     7
Name: runs, Length: 215, dtype: int64

In [30]:
#fancy indexing
vk_series[[1,3,5,7]]

1    23
3    12
5     9
7     0
Name: runs, dtype: int64

In [45]:
#indexing with labels
type(bollywood)

pandas.Series

##Editing series

In [19]:
#using indexing = provides the indexing to change value
marks_series["English"]=100
marks_series

Maths       67
English    100
Hindi       90
Science     89
Name: simran ke marks, dtype: int64

In [20]:
#what if an idex does not exist
marks_series["sst"]=90
marks_series

Maths       67
English    100
Hindi       90
Science     89
sst         90
Name: simran ke marks, dtype: int64

In [28]:
#slicing = chnages the values at 2 to 4 index in which 4 is not included
vk_series[2:4]=[100,100]
vk_series

0        0
1       23
2      100
3      100
4        0
      ...
210      0
211     20
212     73
213     25
214      7
Name: runs, Length: 215, dtype: int64

In [ ]:
#Fancy indexing =change the values at 0,3,4 index 
vk_series[[0,3,4]]=[0,0,0]
vk_series

0        0
1       23
2      100
3        0
4        0
      ...
210      0
211     20
212     73
213     25
214      7
Name: runs, Length: 215, dtype: int64