##Pandas : It is a fast,powerful,flexible and easy to use open source data analysis and manipulation tool,built on top ofthe Python

##Pandas series: It is like a column in table .It is a 1D array holding data of any type

In [4]:
# importing pandas
import pandas as pd
import numpy as np

##Series from lists

In [ ]:
#String
country=["India","Pakistan","USA","Nepal","Srilanka"]
pd.Series(country)

0       India
1    Pakistan
2         USA
3       Nepal
4    Srilanka
dtype: str

In [26]:
#Integer
runs=[12,13,15,17,18,19,19]
pd.Series(runs)

0    12
1    13
2    15
3    17
4    18
5    19
6    19
dtype: int64

In [5]:
#Custom index
marks=[65,78,29,98]
subjects=["Maths","English","Science","Hindi"]
pd.Series(marks,index=subjects)

Maths      65
English    78
Science    29
Hindi      98
dtype: int64

In [18]:
#Setting a name
pd.Series(marks,index=subjects,name="simran ke marks")

Maths      67
English    78
Science    89
Hindi      90
Name: simran ke marks, dtype: int64

##Series from dict

In [21]:
marks={"Maths":67,"English":78,"Hindi":90,"Science":89}
marks_series=pd.Series(marks,name="simran ke marks")
marks_series

Maths      67
English    78
Hindi      90
Science    89
Name: simran ke marks, dtype: int64

##Series Attributes

In [22]:
#size=Number of items in series
marks_series.size

4

In [23]:
#dtype=type of the elemnets in series
marks_series.dtype

dtype('int64')

In [24]:
#name=The we added in the name section of the code
marks_series.name

'simran ke marks'

In [28]:
#is_unique=It will gives true value for unique numbers in series but if it sees the repeated number than gives false
marks_series.is_unique

True

In [29]:
#index=Gives the index values
marks_series.index

Index(['Maths', 'English', 'Hindi', 'Science'], dtype='str')

In [31]:
#value=Gives numpy array
marks_series.values

array([67, 78, 90, 89])

##Series using read_csv

In [7]:
#with one col
subs=pd.read_csv('subs.csv')
subs

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [9]:
#with two cols
vk=pd.read_csv('kohli_ipl.csv')
vk

     match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

In [10]:
#importing movie data
movies=pd.read_csv('bollywood.csv')
movies

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]

In [15]:
#making lead column->index
bolly_data=pd.read_csv('bollywood.csv',index_col='movie')
bolly_data

                                                  lead
movie
Uri: The Surgical Strike                 Vicky Kaushal
Battalion 609                              Vicky Ahuja
The Accidental Prime Minister (film)       Anupam Kher
Why Cheat India                          Emraan Hashmi
Evening Shadows                       Mona Ambegaonkar
...                                                ...
Hum Tumhare Hain Sanam                  Shah Rukh Khan
Aankhen (2002 film)                   Amitabh Bachchan
Saathiya (film)                           Vivek Oberoi
Company (film)                              Ajay Devgn
Awara Paagal Deewana                      Akshay Kumar

[1500 rows x 1 columns]

##Series Methods

In [13]:
#head=gives the top five rows
subs.head()
vk.head(3) #this gives the first 3 rows

   match_no  runs
0         1     1
1         2    23
2         3    13

In [14]:
#tail = This gives last five matches
vk.tail(5)

     match_no  runs
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7