### Wide format is where we have a single row for every data point with multiple columns to hold the values of various attributes (In simple words more columns less rows)

### Long format is where for each data point we have as many rows as the number of attributes and each row contains the value of a particular  attribute for a given data points.(In simple words more rows and less columns)

### melt : This is use to convert Wide data into long data
### pivot : This is use to convert Long data into Wide data

In [2]:
# import 
import numpy as np
import pandas as pd

In [5]:
# melt 
pd.DataFrame({'cse' : [120]})
pd.DataFrame({'cse':[120]}).melt()

  variable  value
0      cse    120

In [6]:
# melt another example:
pd.DataFrame({'cse':[120],'ece':[100],'mech':[150]}).melt(var_name='branch',value_name='num_students')

  branch  num_students
0    cse           120
1    ece           100
2   mech           150