In [1]:
import numpy as np
import pandas as pd

In [9]:
#import the dataset used in this 
courses=pd.read_csv('courses.csv')
students=pd.read_csv('students.csv')
nov=pd.read_csv('reg-month1.csv')
dec=pd.read_csv('reg-month2.csv')
matches=pd.read_csv('matches.csv')
delivery=pd.read_csv('deliveries (1).csv')

In [13]:
#concat : We can vertically stack two datasets using this function
regs=pd.concat([nov,dec])
regs

    student_id  course_id
0           23          1
1           15          5
2           18          6
3           23          4
4           16          9
5           18          1
6            1          1
7            7          8
8           22          3
9           15          1
10          19          4
11           1          6
12           7         10
13          11          7
14          13          3
15          24          4
16          21          1
17          16          5
18          23          3
19          17          7
20          23          6
21          25          1
22          19          2
23          25         10
24           3          3
0            3          5
1           16          7
2           12         10
3           12          1
4           14          9
5            7          7
6            7          2
7           16          3
8           17         10
9           11          8
10          14          6
11          12          5
12          12          7
13          18          8
14           1         10
15           1          9
16           2          5
17           7          6
18          22          5
19          22          6
20          23          9
21          23          5
22          14          4
23          14          1
24          11         10
25          42          9
26          50          8
27          38          1

In [15]:
#But we have one issue in above code that index get repeated so to solve this problem use ignore_index
regs=pd.concat([nov,dec],ignore_index=True)
regs

    student_id  course_id
0           23          1
1           15          5
2           18          6
3           23          4
4           16          9
5           18          1
6            1          1
7            7          8
8           22          3
9           15          1
10          19          4
11           1          6
12           7         10
13          11          7
14          13          3
15          24          4
16          21          1
17          16          5
18          23          3
19          17          7
20          23          6
21          25          1
22          19          2
23          25         10
24           3          3
25           3          5
26          16          7
27          12         10
28          12          1
29          14          9
30           7          7
31           7          2
32          16          3
33          17         10
34          11          8
35          14          6
36          12          5
37          12          7
38          18          8
39           1         10
40           1          9
41           2          5
42           7          6
43          22          5
44          22          6
45          23          9
46          23          5
47          14          4
48          14          1
49          11         10
50          42          9
51          50          8
52          38          1

In [19]:
#And if u want to differentiate between the data but not by index use this instead
multi_idx=pd.concat([nov,dec],keys=['Nov','Dec'])
multi_idx

        student_id  course_id
Nov 0           23          1
    1           15          5
    2           18          6
    3           23          4
    4           16          9
    5           18          1
    6            1          1
    7            7          8
    8           22          3
    9           15          1
    10          19          4
    11           1          6
    12           7         10
    13          11          7
    14          13          3
    15          24          4
    16          21          1
    17          16          5
    18          23          3
    19          17          7
    20          23          6
    21          25          1
    22          19          2
    23          25         10
    24           3          3
Dec 0            3          5
    1           16          7
    2           12         10
    3           12          1
    4           14          9
    5            7          7
    6            7          2
    7           16          3
    8           17         10
    9           11          8
    10          14          6
    11          12          5
    12          12          7
    13          18          8
    14           1         10
    15           1          9
    16           2          5
    17           7          6
    18          22          5
    19          22          6
    20          23          9
    21          23          5
    22          14          4
    23          14          1
    24          11         10
    25          42          9
    26          50          8
    27          38          1

In [21]:
#Multiindex : Accessing only nov index
multi_idx.loc['Nov']

    student_id  course_id
0           23          1
1           15          5
2           18          6
3           23          4
4           16          9
5           18          1
6            1          1
7            7          8
8           22          3
9           15          1
10          19          4
11           1          6
12           7         10
13          11          7
14          13          3
15          24          4
16          21          1
17          16          5
18          23          3
19          17          7
20          23          6
21          25          1
22          19          2
23          25         10
24           3          3

In [22]:
# To access particular data
multi_idx.loc[('Nov',0)]

student_id    23
course_id      1
Name: (Nov, 0), dtype: int64