In [4]:
import numpy as np
import pandas as pd

### As we know that series can fetch 1d dataset and Dataframes can fetch 2d datasets .The question is that can we fetch 3d dataset?

In [5]:
# multiindex dataset
index_val=[('cse',2019),('cse',2020),('cse',2021),('cse',2022),('ece',2019),('ece',2020),('ece',2021),('ece',2022)]
index_val

[('cse', 2019),
 ('cse', 2020),
 ('cse', 2021),
 ('cse', 2022),
 ('ece', 2019),
 ('ece', 2020),
 ('ece', 2021),
 ('ece', 2022)]

In [6]:
a=pd.Series([1,2,3,4,5,6,7,8],index=index_val)
a

(cse, 2019)    1
(cse, 2020)    2
(cse, 2021)    3
(cse, 2022)    4
(ece, 2019)    5
(ece, 2020)    6
(ece, 2021)    7
(ece, 2022)    8
dtype: int64

In [7]:
# The problem ?
#a['cse'] It gives the error because  no single cse index exist ,so the above one is wrong way to create a multi index

#The solution?
# MultiIndex series(also known as Hierarchial indexing)
#MultiIndex levels within a single index

In [8]:
# How to create multiindex object
# 1.pd.MultiIndex.from_tuples
multiindex=pd.MultiIndex.from_tuples(index_val)
multiindex

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

In [9]:
# 2.pd.MultiIndex.from_product()
pd.MultiIndex.from_product([['cse','ece'],[2019,2020,2021,2022]])

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

### Creating  a series with multiindex obj

In [13]:
#How to fetch items from such a series s[('cse','ece')]
#Multiindex series is 2D
#Unstack() : Convert multiindex -> DataFrames
#temp.unstack()
#stack() : Convert DataFrame ->Series
#temp.stack()

### Why should we use Multi index series?
### You can represent the higher dimension data like(3d,4d,5d)into the series and DataFrame

In [11]:
#Multiindex dataframe (Multiindexing on rows)
branch_df1=pd.DataFrame([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12],[13,14],[15,16]],index=multiindex,columns=['avg_package','students'])
branch_df1
branch_df1.loc['cse'] # To fetch the dataset of cse columns

      avg_package  students
2019            1         2
2020            3         4
2021            5         6
2022            7         8

In [19]:
#Are columns really different from index 
#Multiiindex df from columns(3D)persecptive
branch_df2=pd.DataFrame([[1,2,0,0],[3,4,0,0],[5,6,0,0],[7,8,0,0]],index=[2019,2020,2021,2022],columns=pd.MultiIndex.from_product([['delhi','mumbai'],['avg_package','students']]))
branch_df2
branch_df2['delhi']
branch_df2['mumbai']['avg_package']
branch_df2.loc[2019]

delhi   avg_package    1
        students       2
mumbai  avg_package    0
        students       0
Name: 2019, dtype: int64

In [21]:
#Multiindexing on both row and column(4D)
branch_df3=pd.DataFrame([[1,2,0,0],[3,4,0,0],[5,6,0,0],[7,8,0,0],[9,10,0,0],[11,12,0,0],[13,14,0,0],[15,16,0,0]],index=multiindex,columns=pd.MultiIndex.from_product([['delhi','mumbai'],['average_package','students']])
                                                )
branch_df3

                   delhi                   mumbai
         average_package students average_package students
cse 2019               1        2               0        0
    2020               3        4               0        0
    2021               5        6               0        0
    2022               7        8               0        0
ece 2019               9       10               0        0
    2020              11       12               0        0
    2021              13       14               0        0
    2022              15       16               0        0

In [32]:
branch_df1

          avg_package  students
cse 2019            1         2
    2020            3         4
    2021            5         6
    2022            7         8
ece 2019            9        10
    2020           11        12
    2021           13        14
    2022           15        16

In [24]:
#Stacking and Unstacking:
#stack : Column to row convertion
branch_df1.unstack()
branch_df1.unstack().unstack()

avg_package  2019  cse     1
                   ece     9
             2020  cse     3
                   ece    11
             2021  cse     5
                   ece    13
             2022  cse     7
                   ece    15
students     2019  cse     2
                   ece    10
             2020  cse     4
                   ece    12
             2021  cse     6
                   ece    14
             2022  cse     8
                   ece    16
dtype: int64

In [29]:
branch_df3

                   delhi                   mumbai
         average_package students average_package students
cse 2019               1        2               0        0
    2020               3        4               0        0
    2021               5        6               0        0
    2022               7        8               0        0
ece 2019               9       10               0        0
    2020              11       12               0        0
    2021              13       14               0        0
    2022              15       16               0        0

In [31]:
#unstack : Row to Column convertion
branch_df3.stack()
branch_df3.stack().stack()

cse  2019  average_package  delhi      1
                            mumbai     0
           students         delhi      2
                            mumbai     0
     2020  average_package  delhi      3
                            mumbai     0
           students         delhi      4
                            mumbai     0
     2021  average_package  delhi      5
                            mumbai     0
           students         delhi      6
                            mumbai     0
     2022  average_package  delhi      7
                            mumbai     0
           students         delhi      8
                            mumbai     0
ece  2019  average_package  delhi      9
                            mumbai     0
           students         delhi     10
                            mumbai     0
     2020  average_package  delhi     11
                            mumbai     0
           students         delhi     12
                            mumbai     0
     2021  average_package  delhi     13
                            mumbai     0
           students         delhi     14
                            mumbai     0
     2022  average_package  delhi     15
                            mumbai     0
           students         delhi     16
                            mumbai     0
dtype: int64

In [33]:
# Working with multiindex dataframe
branch_df3.head()

                   delhi                   mumbai
         average_package students average_package students
cse 2019               1        2               0        0
    2020               3        4               0        0
    2021               5        6               0        0
    2022               7        8               0        0
ece 2019               9       10               0        0

In [34]:
branch_df3.shape

(8, 4)

In [35]:
branch_df3.info()

<class 'pandas.DataFrame'>
MultiIndex: 8 entries, ('cse', np.int64(2019)) to ('ece', np.int64(2022))
Data columns (total 4 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   (delhi, average_package)   8 non-null      int64
 1   (delhi, students)          8 non-null      int64
 2   (mumbai, average_package)  8 non-null      int64
 3   (mumbai, students)         8 non-null      int64
dtypes: int64(4)
memory usage: 460.0+ bytes

In [36]:
branch_df3.duplicated()

cse  2019    False
     2020    False
     2021    False
     2022    False
ece  2019    False
     2020    False
     2021    False
     2022    False
dtype: bool

In [37]:
branch_df3.isnull()

                   delhi                   mumbai
         average_package students average_package students
cse 2019           False    False           False    False
    2020           False    False           False    False
    2021           False    False           False    False
    2022           False    False           False    False
ece 2019           False    False           False    False
    2020           False    False           False    False
    2021           False    False           False    False
    2022           False    False           False    False

In [38]:
#Extracting rows single
branch_df3.loc[('cse',2022)]

delhi   average_package    7
        students           8
mumbai  average_package    0
        students           0
Name: (cse, 2022), dtype: int64

In [39]:
#multiple rows
branch_df3.loc[('cse',2019):('ece',2020):2]

                   delhi                   mumbai
         average_package students average_package students
cse 2019               1        2               0        0
    2021               5        6               0        0
ece 2019               9       10               0        0

In [41]:
#using iloc
branch_df3.iloc[0]
branch_df3.iloc[0:5:2]

                   delhi                   mumbai
         average_package students average_package students
cse 2019               1        2               0        0
    2021               5        6               0        0
ece 2019               9       10               0        0

In [42]:
#Extracting cols
branch_df3['delhi']

          average_package  students
cse 2019                1         2
    2020                3         4
    2021                5         6
    2022                7         8
ece 2019                9        10
    2020               11        12
    2021               13        14
    2022               15        16

In [43]:
branch_df3['delhi']['students']

cse  2019     2
     2020     4
     2021     6
     2022     8
ece  2019    10
     2020    12
     2021    14
     2022    16
Name: students, dtype: int64