In [4]:
import numpy as np
import pandas as pd

### As we know that series can fetch 1d dataset and Dataframes can fetch 2d datasets .The question is that can we fetch 3d dataset?

In [5]:
# multiindex dataset
index_val=[('cse',2019),('cse',2020),('cse',2021),('cse',2022),('ece',2019),('ece',2020),('ece',2021),('ece',2022)]
index_val

[('cse', 2019),
 ('cse', 2020),
 ('cse', 2021),
 ('cse', 2022),
 ('ece', 2019),
 ('ece', 2020),
 ('ece', 2021),
 ('ece', 2022)]

In [6]:
a=pd.Series([1,2,3,4,5,6,7,8],index=index_val)
a

(cse, 2019)    1
(cse, 2020)    2
(cse, 2021)    3
(cse, 2022)    4
(ece, 2019)    5
(ece, 2020)    6
(ece, 2021)    7
(ece, 2022)    8
dtype: int64

In [7]:
# The problem ?
#a['cse'] It gives the error because  no single cse index exist ,so the above one is wrong way to create a multi index

#The solution?
# MultiIndex series(also known as Hierarchial indexing)
#MultiIndex levels within a single index

In [8]:
# How to create multiindex object
# 1.pd.MultiIndex.from_tuples
multiindex=pd.MultiIndex.from_tuples(index_val)
multiindex

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

In [9]:
# 2.pd.MultiIndex.from_product()
pd.MultiIndex.from_product([['cse','ece'],[2019,2020,2021,2022]])

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

### Creating  a series with multiindex obj

In [13]:
#How to fetch items from such a series s[('cse','ece')]
#Multiindex series is 2D
#Unstack() : Convert multiindex -> DataFrames
#temp.unstack()
#stack() : Convert DataFrame ->Series
#temp.stack()

### Why should we use Multi index series?
### You can represent the higher dimension data like(3d,4d,5d)into the series and DataFrame

In [11]:
#Multiindex dataframe (Multiindexing on rows)
branch_df1=pd.DataFrame([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12],[13,14],[15,16]],index=multiindex,columns=['avg_package','students'])
branch_df1
branch_df1.loc['cse'] # To fetch the dataset of cse columns

      avg_package  students
2019            1         2
2020            3         4
2021            5         6
2022            7         8

In [19]:
#Are columns really different from index 
#Multiiindex df from columns(3D)persecptive
branch_df2=pd.DataFrame([[1,2,0,0],[3,4,0,0],[5,6,0,0],[7,8,0,0]],index=[2019,2020,2021,2022],columns=pd.MultiIndex.from_product([['delhi','mumbai'],['avg_package','students']]))
branch_df2
branch_df2['delhi']
branch_df2['mumbai']['avg_package']
branch_df2.loc[2019]

delhi   avg_package    1
        students       2
mumbai  avg_package    0
        students       0
Name: 2019, dtype: int64

In [21]:
#Multiindexing on both row and column(4D)
branch_df3=pd.DataFrame([[1,2,0,0],[3,4,0,0],[5,6,0,0],[7,8,0,0],[9,10,0,0],[11,12,0,0],[13,14,0,0],[15,16,0,0]],index=multiindex,columns=pd.MultiIndex.from_product([['delhi','mumbai'],['average_package','students']])
                                                )
branch_df3

                   delhi                   mumbai
         average_package students average_package students
cse 2019               1        2               0        0
    2020               3        4               0        0
    2021               5        6               0        0
    2022               7        8               0        0
ece 2019               9       10               0        0
    2020              11       12               0        0
    2021              13       14               0        0
    2022              15       16               0        0

In [22]:
#Stacking and Unstacking:
#stack : Column to row convertion
branch_df1.unstack()

    avg_package                students
           2019 2020 2021 2022     2019 2020 2021 2022
cse           1    3    5    7        2    4    6    8
ece           9   11   13   15       10   12   14   16